name: CI

on: [push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Copy env of Contracts
        run: cp env/.env.sample env/.env
      - name: Check formatting of Contracts
        run: yarn run formatting:check
      - name: Compile of Contracts
        run: yarn run build
      - name: Run Hardhat Tests of Contracts
        env:
          REPORT_GAS: true
        run: yarn run test
